x-env: &env
  TZ: ${TZ}
  PUID: ${PUID}
  PGID: ${PGID}

x-restart: &restart
  restart: unless-stopped

services:
  adguard:
    image: adguard/adguardhome:v0.107.11
    container_name: adguard
    ports:
      - "53:53"       # dns
      - "53:53/udp"   # dns
      - "3000:3000"   # initial setup
      - "8080:80"     # dashboard
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/config:/opt/adguardhome/conf
    <<: *restart

  home-assistant:
    image: homeassistant/home-assistant:2022.4
    container_name: home-assistant
    network_mode: host
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    <<: *restart

  mosquitto:
    image: eclipse-mosquitto:2.0.15-openssl
    container_name: mosquitto
    depends_on: [home-assistant]
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    <<: *restart

  jellyfin:
    image: linuxserver/jellyfin:10.8.4
    container_name: jellyfin
    environment:
      <<: *env
    ports:
      - "8096:8096"
      - "7359:7359/udp" # Allows client discovery on local network
        #- "1900:1900/udp" # DLNA discovery
    volumes:
      - ./jellyfin:/config
      - /home/jonathan/video/tv:/data/tvshows
      - /home/jonathan/video/movies:/data/movies
      - /home/jonathan/video/music_videos:/data/music_videos
      - /home/jonathan/music:/data/music
    <<: *restart

  transmission:
    image: linuxserver/transmission:version-3.00-r5
    container_name: transmission
    environment:
      TRANSMISSION_WEB_HOME: /flood-for-transmission/
      <<: *env
    ports:
      - "9091:9091" # webui
      # torrents
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ./transmission:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    <<: *restart

  uptime-kuma:
    image: louislam/uptime-kuma:1.17.1-alpine
    container_name: uptime-kuma
    ports: ["3001:3001"]
    volumes:
      - ./uptime-kuma:/app/data
    <<: *restart

  navidrome:
    image: deluan/navidrome:0.47.5
    container_name: navidrome
    ports: ["4533:4533"]
    user: 1000:1003
    environment:
      ND_REVERSEPROXYWHITELIST: '10.10.10.1/32'
    volumes:
      - ./navidrome:/data
      - /home/jonathan/music:/music:ro
    <<: *restart

  lldap:
    image: nitnelave/lldap:v0.4
    container_name: lldap
    environment:
      UID: ${PUID}
      GID: ${PGID}
      LLDAP_JWT_SECRET: ${LLDAP_JWT_SECRET}
      LLDAP_LDAP_USER_PASS: ${PASSWORD}
      LLDAP_LDAP_BASE_DN: ${BASE_DN}
    ports:
      - "3890:3890"   # ldap
      - "17170:17170" # web UI
    volumes:
      - ./lldap:/data
    <<: *restart

  authelia:
    image: authelia/authelia:4.36.7
    container_name: authelia
    depends_on: [lldap]
    environment:
      AUTHELIA_DEFAULT_REDIRECTION_URL: https://auth.${DOMAIN}
      AUTHELIA_SESSION_DOMAIN: ${DOMAIN}
      AUTHELIA_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ${PASSWORD}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: ${BASE_DN}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: uid=admin,ou=people,${BASE_DN}
      <<: *env
    ports: ["1000:1000"]
    volumes:
      - ./authelia:/config
    <<: *restart

  vaultwarden:
    image: vaultwarden/server:1.25.2-alpine
    container_name: vaultwarden
    ports:
      - "8081:80"   # webui
      - "3012:3012" # websockets
    environment:
      WEBSOCKET_ENABLED:    'true'
      SIGNUPS_ALLOWED:      'false'
      INVITATIONS_ALLOWED:  'false'
      SHOW_PASSWORD_HINT:   'false'
      <<: *env
    volumes:
      - ./vaultwarden:/data
    <<: *restart

  whoogle:
    image: benbusby/whoogle-search:0.8.0
    container_name: whoogle
    environment:
      WHOOGLE_CONFIG_URL: https://search.${DOMAIN}
      HTTPS_ONLY: 1
      WHOOGLE_RESULTS_PER_PAGE: 20
      WHOOGLE_TOR_SERVICE: 0
    ports: ["1300:5000"]
    <<: *restart
