x-env: &env
  TZ: ${TZ}
  PUID: ${PUID}
  PGID: ${PGID}

x-restart: &restart
  restart: unless-stopped

services:
  adguard:
    image: adguard/adguardhome:v0.107.11
    container_name: adguard
    ports:
      - "53:53"       # dns
      - "53:53/udp"   # dns
      - "3000:3000"   # initial setup
      - "8080:80"     # dashboard
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/config:/opt/adguardhome/conf
    <<: *restart

  home-assistant:
    image: homeassistant/home-assistant:2022.4
    container_name: home-assistant
    network_mode: host
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    <<: *restart

  mosquitto:
    image: eclipse-mosquitto:2.0.14-openssl
    container_name: mosquitto
    depends_on: [home-assistant]
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
