services:
  tuwunel:
    image: jevolk/tuwunel:v1.7.1
    container_name: tuwunel
    ports: ["8448:8008"]  # published port 8448 can't be changed because of federation
    environment:
      TUWUNEL_SERVER_NAME: ${DOMAIN}
      TUWUNEL_DATABASE_PATH: /var/lib/tuwunel
      TUWUNEL_ADDRESS: 0.0.0.0
      TUWUNEL_ALLOW_FEDERATION: 'true'
      TUWUNEL_TRUSTED_SERVERS: '["matrix.org"]'
      TUWUNEL_NEW_USER_DISPLAYNAME_SUFFIX: ''
      TUWUNEL_SUPPRESS_PUSH_WHEN_ACTIVE: 'true'
      TUWUNEL_WELL_KNOWN__CLIENT: https://matrix.${DOMAIN}
      TUWUNEL_IDENTITY_PROVIDER__0__BRAND: auth.${DOMAIN}
      TUWUNEL_IDENTITY_PROVIDER__0__CLIENT_ID: tuwunel
      TUWUNEL_IDENTITY_PROVIDER__0__CLIENT_SECRET: ${TUWUNEL_IDENTITY_PROVIDER__0__CLIENT_SECRET}
      TUWUNEL_IDENTITY_PROVIDER__0__CALLBACK_URL: 'https://matrix.${DOMAIN}/_matrix/client/unstable/login/sso/callback/tuwunel'
      TUWUNEL_IDENTITY_PROVIDER__0__ISSUER_URL: https://auth.${DOMAIN}
      TUWUNEL_IDENTITY_PROVIDER__0__TRUSTED: 'true'
      TUWUNEL_IDENTITY_PROVIDER__0__REGISTRATION: 'true'
      TUWUNEL_IDENTITY_PROVIDER__0__UNIQUE_ID_FALLBACKS: 'false'
      TUWUNEL_LOG: 'debug'
    volumes:
      - ./data:/var/lib/tuwunel
    restart: unless-stopped

  instagram-bridge:
    image: dock.mau.dev/mautrix/meta:v0.5.3
    container_name: instagram-bridge
    depends_on: [tuwunel]
    volumes:
      - ./bridges/instagram:/data
    restart: unless-stopped

  gvoice-bridge:
    image: dock.mau.dev/mautrix/gvoice:v26.05
    container_name: gvoice-bridge
    depends_on: [tuwunel]
    volumes:
      - ./bridges/gvoice:/data
    restart: unless-stopped
