services:
  lldap:
    image: lldap/lldap:v0.6.2-alpine
    container_name: lldap
    environment:
      UID: 1000
      GID: 100
      TZ: America/Phoenix
      #LLDAP_VERBOSE: true
      LLDAP_HTTP_URL: "https://lldap.${DOMAIN}"
      LLDAP_JWT_SECRET: ${LLDAP_JWT_SECRET}
      LLDAP_LDAP_USER_PASS: ${LLDAP_USER_PASS}
      LLDAP_LDAP_BASE_DN: ${BASE_DN}
      LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: true
      LLDAP_SMTP_OPTIONS__SERVER: smtp.purelymail.com
      LLDAP_SMTP_OPTIONS__PORT: 465
      LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: TLS
      LLDAP_SMTP_OPTIONS__USER: noreply@${DOMAIN}
      LLDAP_SMTP_OPTIONS__PASSWORD: ${SMTP_APP_PASSWORD}
      LLDAP_SMTP_OPTIONS__FROM: Do Not Reply <noreply@${DOMAIN}>
      LLDAP_SMTP_OPTIONS__REPLY_TO: Do Not Reply <noreply@localhost>
    ports:
      - "3890:3890"   # ldap
      - "17170:17170" # web UI
    volumes:
      - ./lldap:/data
    restart: unless-stopped

  authelia:
    image: authelia/authelia:4.39.7
    container_name: authelia
    depends_on: [lldap]
    environment:
      DOMAIN: ${DOMAIN}
      PUID: ${PUID}
      PGID: ${PGID}
      X_AUTHELIA_CONFIG_FILTERS: template
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ${LLDAP_USER_PASS}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: ${BASE_DN}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: uid=admin,ou=people,${BASE_DN}
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ${AUTHELIA_HMAC_SECRET}
      AUTHELIA_NOTIFIER_SMTP_PASSWORD: ${SMTP_APP_PASSWORD}
    ports: ["1000:1000"]
    volumes:
      - ./authelia:/config
    restart: unless-stopped
