services:
  soft-serve:
    image: charmcli/soft-serve:v0.7.6
    container_name: soft-serve
    environment:
      SOFT_SERVE_NAME: git.${DOMAIN}
      SOFT_SERVE_INITIAL_ADMIN_KEYS: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFRxSgJBmsOFmOIdrt1qVCZSqeLMs7NzIHsFFZ0XqM0k deck@steamdeck
      SOFT_SERVE_SSH_PUBLIC_URL: "ssh://nas:23231"
    ports:
      - 23231:23231 # ssh
      - 23232:23232 # http
      - 23233:23233 # stats server
      - 9418:9418   # git
    volumes:
      - ./config:/soft-serve
    restart: unless-stopped
