version: ENC[AES256_GCM,data:SQ==,iv:jigBh848WFXQeI2MFgfNs/oIa2b8fFGGt3FHEOI4TKU=,tag:nFaSk+2qKhPjx+tkuTFaig==,type:int]
global:
    server_name: ENC[AES256_GCM,data:ia1sX1bo4Lzx4R7W,iv:/LnGDAYBV7Dlz2QT9O2dGURwqTqaTHioXI5mMlEk0dY=,tag:H34x/aBnJuZF80rE7bOkrA==,type:str]
    key_id: ENC[AES256_GCM,data:L8icukshDTMaslD1,iv:I3bWSzY+fHGfZaQCAypReLjXYAMrEUVf2gGNVfeDGNY=,tag:0LBc4fvSZfyQDav3EOBG4w==,type:str]
    private_key: ENC[AES256_GCM,data:aIxrk1UnGzIHMWeQQ3k=,iv:uYKh05c5bJlyVk1w9ihdJpWfcrPQyNi+e99/2E06AUk=,tag:CrPt0zLjIHFgAN2mHu3acQ==,type:str]
    old_private_keys: []
    key_validity_period: ENC[AES256_GCM,data:ojHPHzD8Uic=,iv:tsWYaSK0v3Q1mHII1/AzpjPFe4wcFcoUoPZ07O0C+oI=,tag:XuvFYAhiYzui0+51/meCpQ==,type:str]
    database:
        connection_string: ENC[AES256_GCM,data:vdtqF70yQSorgPBm0Ab71qvIqDvLwxg/EOG3TII0VmDp9egyS2vEvgqf53Ws+D2lJPY+tX7wzRaJ2UXwSqATvi11dlQ=,iv:LRS3z2GPXWWf/SLPLGQ8Cz06TITmxm+vCIaYy2yWLnw=,tag:t9bT2DLAElYSC0DEiLQb7g==,type:str]
        max_open_conns: ENC[AES256_GCM,data:cRM=,iv:s59zeqbpC+jtYFlE5r0KdpNNF9eV000BejA/vw3aUm4=,tag:Ts32cgYoavtCQ0q4U0HMLw==,type:int]
        max_idle_conns: ENC[AES256_GCM,data:Jw==,iv:dEbLvytYmASms4u/JDz5Y9j0dLkAYbEetkcFKPjSWj4=,tag:t3T3Qg5GIfURHeZ803oNPQ==,type:int]
        conn_max_lifetime: ENC[AES256_GCM,data:Lzw=,iv:WJFk7bm6UIyR2NppVLZJr9HUS6JgPdrvSg1QGXCMIAM=,tag:HaHAyTgw1rj86JuSikqryA==,type:int]
    well_known_server_name: ""
    well_known_client_name: ""
    well_known_sliding_sync_proxy: ""
    disable_federation: ENC[AES256_GCM,data:THymu4g=,iv:VQNpTO1pBm2GIcfvOHjPLfNCyLyKD7ucHlOuf4IB60E=,tag:WuLY4zwAUJ8JLrynepwreQ==,type:bool]
    presence:
        enable_inbound: ENC[AES256_GCM,data:BX0XUnU=,iv:yEsWXhxpUQl20sKpzw135ObgJNH37wAlkDML72uKikY=,tag:ibvieaX7UmXNVqxQEwwEzg==,type:bool]
        enable_outbound: ENC[AES256_GCM,data:CuKLHTM=,iv:RWVUtcwStyH6F74UAAy/k6nFPIzBuAvs9vhtAaxfyHA=,tag:Ep08kmQM9Eo3wCV3lzV6OQ==,type:bool]
    trusted_third_party_id_servers:
        - ENC[AES256_GCM,data:PYrjHzHri0GpiQ==,iv:H8jdWJKy4sWM9cMJrXTAFJqwOKIRdTC561i6V2OeWUs=,tag:vQGLBJq3e99jXmb6WXEg+A==,type:str]
        - ENC[AES256_GCM,data:ndRu4/vvptBj,iv:Th+o7He2VgO2ShOQTzzPag9eem7Unjokz1ZSwVO1ZjQ=,tag:i+vNaNbRBNp/mnCI6b+BhA==,type:str]
    jetstream:
        storage_path: ENC[AES256_GCM,data:DmEBAsCFTrdiQbqp2WQ=,iv:mszWnar4T7mcdq8eSFVeahGgcbPSm0FfO9sMICUoHTQ=,tag:+B/euLfzqCzXbWAMBNrYgA==,type:str]
        addresses: []
        topic_prefix: ENC[AES256_GCM,data:1AOjIuSw2KM=,iv:f0p1IXXKUPVta0FCjCZQv7lZIUMfiwbpIQxXG+cG+14=,tag:Px9uAlnpbkr2QZ9Fw1BmNQ==,type:str]
        in_memory: ENC[AES256_GCM,data:hDKgQyU=,iv:3uHqof+PF3vDxGGfhICtUopWT5zFdgWo55USfylPD3g=,tag:Ivko129Y4hmQ/z9N1WI1mA==,type:bool]
        disable_tls_validation: ENC[AES256_GCM,data:GOyl6w==,iv:LGEDAhuSuXZR4DaY8rLdDkV2LuMITcTjcwb7fjjQZd8=,tag:6arBH3Wf8k2wALVWkZ1d6A==,type:bool]
    metrics:
        enabled: ENC[AES256_GCM,data:Wuc21iI=,iv:CTeo9xrBJlrWWeeNujcR3SySUpTrO0dMNLp87AYumSA=,tag:RIguPzupFYmAq5zLciuwvQ==,type:bool]
        basic_auth:
            username: ENC[AES256_GCM,data:BMUb8wQA0w==,iv:YmrZtXUlmvpKdHnUWxNxa6RiYm1JoknA5NwvIDrWT5c=,tag:cQqxCTzcrMhCcqkftkLCtQ==,type:str]
            password: ENC[AES256_GCM,data:KtDOYHh9GQ==,iv:0z5ZDC4XhJzAKTIpPzuIxT4RwPCeCWhZPVoV1wLVbIc=,tag:7lD2zQdGrVNeTy1fbsCCEA==,type:str]
    sentry:
        enabled: ENC[AES256_GCM,data:IK0YedI=,iv:ueDi53rIookE0qfH9S9+QUTM+PShPkL4Hp4wq9WEKso=,tag:f2YSG0FAB1Q0qmZ4AGKeOA==,type:bool]
        dsn: ""
        environment: ""
    dns_cache:
        enabled: ENC[AES256_GCM,data:ifCmNbU=,iv:Da/Al4saHFo2ev01fha8artT3RaBvZwVGbhS4W4V6HQ=,tag:HG5fI/bmwCksc8tflfFylw==,type:bool]
        cache_size: ENC[AES256_GCM,data:ebu5,iv:WzTSnA4wFlyDrP6FCNBvupp09NTaWMCrVuOhaidkjOk=,tag:e75gHKpM5JD01/Kz2KlyLQ==,type:int]
        cache_lifetime: ENC[AES256_GCM,data:QUOlSg==,iv:CT40OViZ6ABzbrkV4VVzgkM3Qof2MnvCe8FvYm2/dMg=,tag:7qpHlhmve6wP0H4GWgJWfA==,type:str]
    server_notices:
        enabled: ENC[AES256_GCM,data:TD6NSw==,iv:THhh4Z+sniiFjsRX+woPyLLj0KYjkslRQGvTNxHm0tQ=,tag:UyRmyeEhrz+SNL1Vh0fAyg==,type:bool]
        local_part: ENC[AES256_GCM,data:Rzt4eU8QIA==,iv:DPZk95DNABle+wQ14NphhYQn2ll8W32mdpXJiV7YdOE=,tag:lNJeUdXr/SPA2IBKGw2blQ==,type:str]
        display_name: ENC[AES256_GCM,data:QTzzwXNuxUrq8gfQ,iv:KQyz7zs8pNA9yy3jy6DR0HxHBsjKEf436sla3RxHZQo=,tag:DAv66S7FokGF7K1/3Ghqow==,type:str]
        avatar_url: ""
        room_name: ENC[AES256_GCM,data:ewN6vpY+nmTuHh2m,iv:pMZ6+aXXH0ye/5PJ1PXHLZBmflj+e69kvGmBoiGhskM=,tag:+osXR5BGPbumS0M2qy+sjw==,type:str]
    report_stats:
        enabled: ENC[AES256_GCM,data:y/+ybUo=,iv:ZaRhV0BL4QzLQNeWJD6xN5i4dizVvH9Jh8e64SJitNc=,tag:2wr+VZX29w4BHpMcqzTBiw==,type:bool]
        endpoint: ENC[AES256_GCM,data:cNTxL859z65mdI91RkpAoVR7mPW/Pe9d2mH+uXRpXaLwJQ==,iv:ti77FOiXgYyer40aPDQeiSpb71FfVgqYym0XG1UcCM4=,tag:6lEgi/zXjEb8ws7U5OgF0Q==,type:str]
    cache:
        max_size_estimated: ENC[AES256_GCM,data:pKKrOO+XxK8zPw==,iv:mcEsCKZSpzfVNpivDAvSyt26c49QzY5SD1/lWKe4R5Q=,tag:ixqvih/qY0iEKT+Vr3i5Vw==,type:int]
        max_age: ENC[AES256_GCM,data:n7L1BCum,iv:Q1Cu7sdJdec51gOcQjntb0VhyEMZ5c1H4EAIU4c9icQ=,tag:n1RwP1f21n+DNp2iSUFOBQ==,type:str]
app_service_api:
    disable_tls_validation: ENC[AES256_GCM,data:eTGa0GI=,iv:g52ewMn1e45W/eim5PsL7Ib1C/IfpgIUrfILD6iujzk=,tag:u3IzdbPyGPJ+Ugf5UjUiIA==,type:bool]
    legacy_auth: ENC[AES256_GCM,data:137Eujw=,iv:AAboqaU8/SmwBslBGC+e80fpfyhE+IkOemQDqs6Xb6c=,tag:twO16BBLPgp33ots4MDQYw==,type:bool]
    legacy_paths: ENC[AES256_GCM,data:5ha8TWo=,iv:11lTXmNH/U3+DhswYKkW6z9OjW7unBtguklWAd7yuEs=,tag:J6F3D9F2LSMIv+0Y8i4smA==,type:bool]
    config_files: []
client_api:
    registration_disabled: ENC[AES256_GCM,data:EQpM9w==,iv:4K3zasugGUoNKwcZtGGCUF0XUEpc3X73yleLd/tHPX8=,tag:fUn7S4uHWsjIFtjY45eLew==,type:bool]
    registration_requires_token: ENC[AES256_GCM,data:XW9AgVg=,iv:innGdQW0qxxHjXpjgqkhnKhAq4zTrTaqFqQQ13DlUVU=,tag:ihgq8DF0rvTOvsdRwV+jSA==,type:bool]
    registration_shared_secret: ENC[AES256_GCM,data:crtLE/MIKnkakHVg900=,iv:vk0JEZsYDA01mRdES6g5oPCTJF37SS/CfwXf4K/Yi7M=,tag:RCtAlRyZV27gNdX9TmZjEA==,type:str]
    guests_disabled: ENC[AES256_GCM,data:Cj1LaX4=,iv:nor82lUbYbw6dFUjpSuaqHAGcTWuqlIjYa3+Ei2zEpI=,tag:4qHefI0TKV5HfTkFeiiCCA==,type:bool]
    enable_registration_captcha: ENC[AES256_GCM,data:VY8YEeo=,iv:giPVKPnayDNJLGJNmi7ORBc1Y+evYuFyJYartcEsTns=,tag:oOKbRrSSGl3TyI63B6TMtA==,type:bool]
    recaptcha_api_js_url: ""
    recaptcha_sitekey_class: ""
    recaptcha_form_field: ""
    recaptcha_public_key: ""
    recaptcha_private_key: ""
    recaptcha_bypass_secret: ""
    recaptcha_siteverify_api: ""
    turn:
        turn_user_lifetime: ""
        turn_uris: []
        turn_shared_secret: ""
        turn_username: ""
        turn_password: ""
    rate_limiting:
        enabled: ENC[AES256_GCM,data:BCCh3A==,iv:G5IE44sHZGx0ShP+S2YxeP7cSmSeD3Kn06zrK3fTglY=,tag:auSh8H9kNEpp7KRWJN4vZA==,type:bool]
        threshold: ENC[AES256_GCM,data:Fg==,iv:NLkS4WyxLesWuRwkUvJLRSOE0o4M7Y28T99YCWCC8DI=,tag:CABw+yXPF8mEAqZl9n/W9g==,type:int]
        cooloff_ms: ENC[AES256_GCM,data:Cx/g,iv:7ch7HW4QlXF881m1QiYwzj+TMO9csKW0JFMXZoLzs9Y=,tag:e/tpGYrAjnxMRrDt8yZ3zg==,type:int]
        exempt_user_ids: []
federation_api:
    send_max_retries: ENC[AES256_GCM,data:OsU=,iv:+B6fxlHBcyMXjeXZSZH/1gPFa21aM4UuBnHacFDBg4A=,tag:mb6k+nrKsd+G4Y++ytiEnQ==,type:int]
    enable_relays: ENC[AES256_GCM,data:QuY0lVs=,iv:SPWnF0+NrHjckZtzbyrPl5A1FFBG1hUj1zOporkZDI4=,tag:J6z5DbE3gHei3LvCTZXWig==,type:bool]
    p2p_retries_until_assumed_offline: ENC[AES256_GCM,data:xQ==,iv:fGZDBban+qnFWqIvPWWh2L6+/eeQfuljQf+9sMuzgL0=,tag:i/0GF0v14WwcnwR1X5753Q==,type:int]
    disable_tls_validation: ENC[AES256_GCM,data:znWECJM=,iv:cLsxnr2N6AKhiBG6jAzrkYrghNximPHlj0aMc77N45M=,tag:20DSPrA8piwV644vUdmcIw==,type:bool]
    disable_http_keepalives: ENC[AES256_GCM,data:Q0ou+hM=,iv:9Y7Gmtgfq4LkOd9QyLEVbfVUHZc5PoKg/OrsX/quBqY=,tag:uRnPPP9LufH/W2YRr+Kpfw==,type:bool]
    key_perspectives:
        - server_name: ENC[AES256_GCM,data:Z7NcUQzIOD4blQ==,iv:u8EEe51LB5WKm8rl6SZfMYI9uK7krvW3xzvLv2aVsHo=,tag:3AmdwzzOflDkP2wff14j6g==,type:str]
          keys:
            - key_id: ENC[AES256_GCM,data:vqry3qBadST/01pa,iv:IGFMtTeZEvSET85zRdmGnn8ME8FMEVAsuORIu1/81HQ=,tag:H2J/fdDcIJip8/sBrMUKJw==,type:str]
              public_key: ENC[AES256_GCM,data:qIjfhCIMEd/nFAtHdythJsZxCoy+fdynkl1rUTOQA0vrwx1tNeX5+qkHZQ==,iv:kaXt0W/+tZQlcsHO2bAfAgF1LnxOmSFxaKHap62MgxQ=,tag:12eCrWPcMQlb2taw/prAcw==,type:str]
            - key_id: ENC[AES256_GCM,data:Oo24gtdbXotirqU9KMY=,iv:6HuJxnCfH3VYS/ZdsfEcj/VkDRcqZsdz5vryifSOAtY=,tag:dvXmu/KU7PHSiECR4MIwjA==,type:str]
              public_key: ENC[AES256_GCM,data:6GbEr5LegXtOgsv2/hUYzkRk9fnywb8XNF7Htjf3oqTA32jRvsot7mQiOA==,iv:ZjNMmR2enIEGrMsfoJJF1i3RoRf2/vTAqw3lxZJIt5c=,tag:vseIsUyGgZaMRfLkuNTFjQ==,type:str]
    prefer_direct_fetch: ENC[AES256_GCM,data:Fz/hx0E=,iv:FjFZlnZob4DNEu7kRnscMrs6HIKYFY+fJy8xyV0y3WI=,tag:ueALCbR5Dvkl/wPFLZdjQw==,type:bool]
key_server: {}
media_api:
    base_path: ENC[AES256_GCM,data:CkYJOJs9jMp5m4S+5GRmRZeXwQ==,iv:Lra+dhHmkKNFptQEZWYqIiFqOOCyAAEJ/Kn/HMeFNdw=,tag:75rqGTD5cVIomG8gI9P2/w==,type:str]
    max_file_size_bytes: ENC[AES256_GCM,data:Is1V26uOYN4=,iv:GHooNkwb+Tbw8AnYP5T1a5i+cDIqWColVQ+3zCaq0m8=,tag:jIrBdRvP2hydlYqN9TlIsg==,type:int]
    dynamic_thumbnails: ENC[AES256_GCM,data:9PLDG04=,iv:+7C5TleSinXWbuKzRWKYSF//dsuaT4nq/0bQDFsd7Fs=,tag:mkSjckFILzHJgtr4NsjeNQ==,type:bool]
    max_thumbnail_generators: ENC[AES256_GCM,data:G/g=,iv:77uNnAIe16CPaDAcG4d51mzGE8IXo572UbKJv1NU43c=,tag:lCSIWeNS94p+VR0p6DCVoQ==,type:int]
    thumbnail_sizes:
        - width: ENC[AES256_GCM,data:lSw=,iv:BHlkiYI4Q7WoLMLOlTLoiwcDln2+EZr54gU9fwQrGMA=,tag:0fdvaoE0RRtMlv68YiB4HA==,type:int]
          height: ENC[AES256_GCM,data:45w=,iv:OAP/UPwSSQeA0PrfOuczs9mcQFvoSM/RL/K4Fo2kXQs=,tag:LbjL2Ho+dkuu+9VzCOuwSw==,type:int]
          method: ENC[AES256_GCM,data:Od5Kfw==,iv:PzSjtXAGIxmUfxYCZJ/CamEEFT00s0/mQx0hdn1M8a4=,tag:HrmcYFTbSOOymdGyronDIA==,type:str]
        - width: ENC[AES256_GCM,data:Lls=,iv:YKP9Qh5+C3Bf8PfmX/45TQULmqXTGMWCP70NkEWKprs=,tag:EBb2TtQCu7wW7+s/Zsd1rw==,type:int]
          height: ENC[AES256_GCM,data:XSY=,iv:qQ1SW0Eg5TwbdidfHY0gonIz7h5FIKNG5/ZDOZrSaPs=,tag:66dCbZBtXeZRH+BaqiUIKw==,type:int]
          method: ENC[AES256_GCM,data:7GkpEA==,iv:U4HdNWi6eC6l5uh6QjQzYNMZo+g8TP59/g1X/UIX6do=,tag:hNGJkPH9Zq+FN+a28Wau1A==,type:str]
        - width: ENC[AES256_GCM,data:ms42,iv:ei7TDnpLdTJmIqm7QGxfHRc4JYM+dMHthSWT8o5zRv0=,tag:Sk4NLbiEVfug2L8FBa8BrA==,type:int]
          height: ENC[AES256_GCM,data:p1nN,iv:7d7rqTQTQDLzVUEk39V0wUU8z/u0SHEMLEL+fIP0yG4=,tag:Xko7xEphslxDB0kWbv9h2w==,type:int]
          method: ENC[AES256_GCM,data:PCnn77U=,iv:EYPYrliluPdgBY5gcB55r4RTGHUBz76uDD1ZddswBlQ=,tag:Hu4p8oaaqCyvd1ZPEnTpbA==,type:str]
room_server:
    default_room_version: ENC[AES256_GCM,data:3/k=,iv:mFpo2gwT6nYJfIrG3/u4AncV0CE0DwORU1Pxso0TcEk=,tag:Xd3yEzoHqwjjiPlCxZi5BQ==,type:str]
sync_api:
    real_ip_header: ""
    search:
        enabled: ENC[AES256_GCM,data:+NgFxbA=,iv:Jb2CEMNS53xRruUDEiVHmQn0+Rk+E60w5dJaxzJAo+A=,tag:FYKpDolj9EHA06tYP4shqw==,type:bool]
        index_path: ENC[AES256_GCM,data:vvkZg0jf45BOvSwa295U9B3WvH4bpH96Xw==,iv:St6MZfTlQ5aAmCmf1veqe9kLxEemV0olFNWFXquae8I=,tag:VaIUD7FDWoVhdLyylQCUWQ==,type:str]
        in_memory: ENC[AES256_GCM,data:YTnlGXg=,iv:ub+6K4aPIepIJingRBvnXvhKFpCneZa3JaxOJfJ0Qm4=,tag:v3BQoszpCiYw2SwPptvnnw==,type:bool]
        language: ENC[AES256_GCM,data:mDo=,iv:GqqclK8DfNn3qXsXpGar6luvInD4J+po+2/eAZjSRVU=,tag:Mtjc7uJ2n79GslpckELfXA==,type:str]
user_api:
    bcrypt_cost: ENC[AES256_GCM,data:pyw=,iv:FbceH9xcmiG6xoJfWSbF4mp3uoIkCsnGrO1U3W0sARY=,tag:rtdIlxlyXzZu42kzee/ySg==,type:int]
    openid_token_lifetime_ms: ENC[AES256_GCM,data:eonRg4Bcbw==,iv:yed23GQ3alO5pQukb8Yg26ZVBDGQO/747LComByyQcs=,tag:Cd5KGDmeZorG0SQzlrDlbQ==,type:int]
    push_gateway_disable_tls_validation: ENC[AES256_GCM,data:wjqIymE=,iv:IsInBAZGtn9eoBFDwiZ6hhuaLYEY/LfqSyzXmaCXXPU=,tag:qhPd138dsM75Rqnb2oSRYQ==,type:bool]
    auto_join_rooms: []
    worker_count: ENC[AES256_GCM,data:oQ==,iv:L0XqJ8/SmM+lb1cfitsmxdSI/fPNFyCnCXyHXkjH2PE=,tag:0omNewomz+M1wZHfSD3ijg==,type:int]
relay_api: {}
mscs:
    mscs: []
tracing:
    enabled: ENC[AES256_GCM,data:bKIXBBM=,iv:x659TvrQrIBKPwcCjEqaqDMQ/gFvLEFuWKJ3PBP8o6E=,tag:4xyPDgXYgsSV7TvOxgNdZg==,type:bool]
    jaeger:
        serviceName: ""
        disabled: ENC[AES256_GCM,data:DQj8FV8=,iv:2iov5VCd9WWCjnDBbhhMF1o1glQg5irzEiKUQwUCV5U=,tag:6M27vOhGlnrZ36roOSfnNw==,type:bool]
        rpc_metrics: ENC[AES256_GCM,data:7pS0O7A=,iv:maph3xSegry9TvhNp4TKOAkf7H0Mwu3oN/pSUL8SESg=,tag:zH4RDxou9TM1MKXOC5GGXA==,type:bool]
        traceid_128bit: ENC[AES256_GCM,data:4+oK+5U=,iv:FIJAfMZXrf++jD+4AH4gQcjWLzMmX7vAVcUHZAQGc+g=,tag:0QFiJ1fV5n0a/Dl8i8Bbpg==,type:bool]
        tags: []
        sampler: null
        reporter: null
        headers: null
        baggage_restrictions: null
        throttler: null
logging:
    - type: ENC[AES256_GCM,data:I6Ehjw==,iv:8Fq21oheXrYe+KrgBS/qXSGTlKWYLZZKUpef+Dm1fxc=,tag:9RXFL7VGp3uLRZPe01PnqA==,type:str]
      level: ENC[AES256_GCM,data:C/y22A==,iv:JCr6AcsOHejIQR25Xx2C61U4uluEagZFK2vVPj/Dv2U=,tag:CnakYThxiFGEIBmEpFugeQ==,type:str]
      params:
        path: ENC[AES256_GCM,data:0AIxkuU2jVmWJTkAbj3Hr0k=,iv:tSMbbqqQgvMpEHWNqOmW8R2GrbgGcyD9mDExrH45Gqc=,tag:kDMylQ2ltiQ7F+hfdsk8FQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19pnsu5cj5y30lk022x459ne8mrfkzylcha0k4c8nmj93f7nnkajstqz0cy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL050UHcvTjdURkNPaGlw
            RzlNWld3cGVkcUVPaFhYQmNFTUFZdFkrSnlvCnhXb0VQcVZ0Q2JxT3FybVVqNEU1
            T2JNNVUrWDR4THUrV0ZCUmE5S0Fta3MKLS0tIDA0YUpHc3E0a1NZNG5LY1g5UkJ6
            WnJZMWVYSm0xZjRaVDJwU1psWFVuSkUKBnW55qJZnZJlbYIR6koe+j4MEJImk/EK
            e+HOA15qvRMHM3TgtoV9yvVjcJ3cLqTA9GvojHeeH/RONJznKOVlFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T02:57:24Z"
    mac: ENC[AES256_GCM,data:DUlKqVndEYcjeRUjfbhHD96u5PsX0oE69H2eunvkbFTu2k7cvCisY9ysrrH18weJao6AXVAmK/hjuGbBv/sgDrF3ExRZ9rRkeWrYAKiB7dzzQCbWhtkjh2k2c7fGkgbOA6EGGe8fLQsoSDXxfXsdVTkbJ6/p5IPtOJnuco3rt/U=,iv:2eyDP/EE7ySgPwIxtWYi5ynO9ggJVh3c7UUh0nhS8GM=,tag:CXsnAJeLRzM6gxeXGn708Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
