services:
  navidrome:
    image: deluan/navidrome:0.60.3
    container_name: navidrome
    ports: ["4533:4533"]
    user: 1000:100
    environment:
      ND_EXTAUTH_TRUSTEDSOURCES: 0.0.0.0/0
      ND_ENABLESHARING: 'true'
      ND_ENABLEINSIGHTSCOLLECTOR: 'false'
      ND_ENABLEUSEREDITING: 'false'
    volumes:
      - ./data:/data
      - /mnt/data/media/music:/music:ro
    restart: unless-stopped
