services:
  navidrome:
    image: deluan/navidrome:0.55.2
    container_name: navidrome
    ports: ["4533:4533"]
    user: 1000:100
    environment:
      ND_REVERSEPROXYWHITELIST: '100.64.0.0/24' # tailscale subnet range
      ND_ENABLESHARING: 'true'
      ND_ENABLEINSIGHTSCOLLECTOR: 'false'
      ND_ENABLEUSEREDITING: 'false'
    volumes:
      - ./data:/data
      - /mnt/data/media/music:/music:ro
    restart: unless-stopped
