x-env : &env
  TZ: America/Phoenix
  PUID: 1000
  PGID: 100

x-time: &time /etc/localtime:/etc/localtime:ro

x-restart: &restart
  restart: unless-stopped

services:
  jellyfin:
    image: linuxserver/jellyfin:10.11.5
    container_name: jellyfin
    ports: ["8096:8096"]
    environment:
      <<: *env
    volumes:
      - ./jellyfin/config:/config
      - /mnt/data/media:/media
    devices: ["/dev/dri:/dev/dri"]  # intel quicksync hardware acceleration
    <<: *restart

  deluge:
    image: linuxserver/deluge:2.2.0-r1-ls348
    container_name: deluge
    ports:
      - "8112:8112"   # web ui
      - "6881:6881"
      - "6881:6881/udp"
      - "58846:58846" # thin client
    environment:
      <<: *env
    volumes:
      - ./deluge/config:/config
      - /mnt/data/torrents:/data/torrents
    <<: *restart

  radarr: # movies
    image: linuxserver/radarr:5.27.5.10198-ls283
    container_name: radarr
    ports: ["7878:7878"]
    environment:
      <<: *env
    volumes:
      - ./radarr:/config
      - /mnt/data:/data
    <<: *restart

  sonarr: # tv
    image: linuxserver/sonarr:4.0.15.2941-ls293
    container_name: sonarr
    ports: ["8989:8989"]
    environment:
      <<: *env
    volumes:
      - ./sonarr:/config
      - /mnt/data:/data
    <<: *restart

  prowlarr: # indexers
    image: linuxserver/prowlarr:2.1.5.5216-ls131
    container_name: prowlarr
    ports: ["9696:9696"]
    environment:
      <<: *env
    volumes:
      - ./prowlarr:/config
    <<: *restart

  jellyseer:  # requests
    image: fallenbagel/jellyseerr:preview-OIDC
    container_name: jellyseer
    ports: ["5055:5055"]
    environment:
      <<: *env
    volumes:
      - ./jellyseer:/app/config

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.30.0
    container_name: audiobookshelf
    ports: ["13378:80"]
    environment:
      <<: *env
    volumes:
      - /mnt/data/media/books:/audiobooks
      - /mnt/data/media/podcasts:/podcasts
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
    <<: *restart

  audiobookrequest:
    image: markbeep/audiobookrequest:1.8.0
    container_name: audiobookrequest
    ports: ["13379:8000"]
    environment:
      ABR_APP__INIT_ROOT_USERNAME: admin
      ABR_APP__INIT_ROOT_PASSWORD: ${audiobookrequest_password}
    volumes:
      - ./audiobookrequest:/config
    <<: *restart
