x-env : &env
  TZ: America/Phoenix
  PUID: 1000
  PGID: 100

x-time: &time /etc/localtime:/etc/localtime:ro

x-restart: &restart
  restart: unless-stopped

services:
  jellyfin:
    image: linuxserver/jellyfin:10.11.11
    container_name: jellyfin
    ports: ["8096:8096"]
    environment:
      <<: *env
    volumes:
      - ./jellyfin/config:/config
      - /mnt/data/media:/media
    devices: ["/dev/dri:/dev/dri"]  # intel quicksync hardware acceleration
    <<: *restart

  deluge:
    image: linuxserver/deluge:2.2.0-ls381
    container_name: deluge
    ports:
      - "8112:8112"   # web ui
      - "6881:6881"
      - "6881:6881/udp"
      - "58846:58846" # thin client
    environment:
      <<: *env
    volumes:
      - ./deluge/config:/config
      - /mnt/data/torrents:/data/torrents
    <<: *restart

  radarr: # movies
    image: linuxserver/radarr:6.3.0.10514-ls311
    container_name: radarr
    ports: ["7878:7878"]
    environment:
      <<: *env
    volumes:
      - ./radarr:/config
      - /mnt/data:/data
    <<: *restart

  sonarr: # tv
    image: linuxserver/sonarr:4.0.19.2979-ls320
    container_name: sonarr
    ports: ["8989:8989"]
    environment:
      <<: *env
    volumes:
      - ./sonarr:/config
      - /mnt/data:/data
    <<: *restart

  prowlarr: # indexers
    image: linuxserver/prowlarr:2.4.0.5397-ls154
    container_name: prowlarr
    ports: ["9696:9696"]
    environment:
      <<: *env
    volumes:
      - ./prowlarr:/config
    <<: *restart

  seerr:  # watch requests
    image: seerr/seerr:preview-new-oidc
    container_name: seerr
    ports: ["5055:5055"]
    environment:
      <<: *env
    volumes:
      - ./seerr:/app/config
    <<: *restart

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.30.0
    container_name: audiobookshelf
    ports: ["13378:80"]
    environment:
      <<: *env
    volumes:
      - /mnt/data/media/books:/audiobooks
      - /mnt/data/media/podcasts:/podcasts
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
    <<: *restart

  audiobookrequest:
    image: markbeep/audiobookrequest:1.8.0
    container_name: audiobookrequest
    ports: ["13379:8000"]
    environment:
      ABR_APP__INIT_ROOT_USERNAME: admin
      ABR_APP__INIT_ROOT_PASSWORD: ${audiobookrequest_password}
    volumes:
      - ./audiobookrequest:/config
    <<: *restart

  profilarr:  # video quality config
    image: ghcr.io/dictionarry-hub/profilarr:2.0.9
    container_name: profilarr
    depends_on: [sonarr, radarr]
    ports: ["6868:6868"]
    environment:
      <<: *env
      AUTH: off
    volumes:
      - ./profilarr:/config
    <<: *restart
