- id: turn_on_porch_lights
  alias: "Turn on porch lights 30 min. before sunset"
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    service: homeassistant.turn_on
    target:
      entity_id: light.porch_lights
- id: turn_off_porch_lights
  alias: "Turn off porch lights 30 min. after sunrise"
  trigger:
    - platform: sun
      event: sunrise
      offset: "+00:30:00"
  action:
    service: homeassistant.turn_off
    target:
      entity_id: light.porch_lights
