# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Light groups
light:
  - platform: group
    name: Living Room Lights
    entities:
      - light.yeelight_color_0x53855bf
      - light.yeelight_color_0x53857f5
  - platform: group
    name: Bedroom Lights
    entities:
      - light.tasmota_2
      - light.tasmota_3
  - platform: group
    name: Porch Lights
    entities:
      - light.tasmota
