default_config: # Loads default set of integrations. Do not remove.

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: home
  unit_system: metric
  currency: USD
  country: US
  time_zone: !env_var TZ

# Text to speech
tts:
  - platform: google_translate

# Light groups
light:
  - platform: group
    unique_id: living_room_lights
    name: Living Room Lights
    entities:
      - light.yeelight_color_0x53855bf
      - light.yeelight_color_0x53857f5
  - platform: group
    unique_id: bedroom_lights
    name: Bedroom Lights
    entities:
      - light.tasmota_2
      - light.tasmota_3
  - platform: group
    unique_id: porch_lights
    name: Porch Lights
    entities:
      - light.tasmota
